Add tariff information to channel available in sites
madpilot/amberelectric.py pull request #8
Opened 2023-07-18 00:04 UTC by iconnor

While waiting for my smart meter, I noticed my cost was more than a friend's. When I dug into this, I found that my site's tariff was higher. This information is available on the site's channel, so I have updated the code so this can also be seen through the Python wrapper to the API.

![image](https://github.com/madpilot/amberelectric.py/assets/22875/6681bdc7-16a7-43fa-8845-17e9a7432868)

2023-07-18 00:09 UTC, madpilot approved these changes

2023-07-18 01:32 UTC, iconnor commented
Did you want me to update the tests to use more modern pythons? 3.6 should probably go and now start at 3.7 and cover 3.9, 3.10 and 3.11?

2023-07-19 10:26 UTC, madpilot commented
Yes, please - and if you can update the test to check for the new attribute that would be ace.

2023-08-14 23:56 UTC, iconnor commented
Locally the tests now pass:
```bash
pytest
================================ test session starts ================================
platform linux -- Python 3.7.12, pytest-7.1.2, pluggy-0.13.1
rootdir: /home/iconnor/workspace/iconnor/amberelectric.py
plugins: mock-3.8.2, doctestplus-0.12.0, astropy-0.10.0, remotedata-0.3.3, hypothesis-6.36.0, astropy-header-0.1.2, filter-subpackage-0.1.1, arraydiff-0.3, openfiles-0.5.0, cov-3.0.0, anyio-3.6.1
collected 7 items                                                                   

test/test_amber_api.py .......                                                [100%]

================================= 7 passed in 0.06s =================================

```

2023-11-08 04:21 UTC, madpilot commented
No pandas please, there is zero reason for that to be in this package.

2023-11-08 04:22 UTC, madpilot commented
And how do timezones break things?

2023-11-28 23:44 UTC, madpilot requested changes

2023-11-28 23:44 UTC, madpilot commented on amberelectric/api/amber_api.py
> +import pandas as pd
This doesn't belong in this API.

2023-11-28 23:44 UTC, madpilot commented on amberelectric/api/amber_api.py
> +    def get_usage_dateframe(self, site_id: str, start_date: date, end_date: date, **kwargs):
Doesn't belong in this API.

2023-11-28 23:44 UTC, madpilot commented on requirements.txt
> +pandas >= 1.1.4
Please remove

2023-11-29 01:20 UTC, madpilot commented
Superseeded by https://github.com/madpilot/amberelectric.py/pull/9

2023-11-29 01:20 UTC, closed without merging

2024-04-21 23:18 UTC, iconnor commented
Sorry about neglecting this PR; I switched to LocalVolts to get five-minute windows.